apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./ml-scoring/deployment.yaml
  - ./ml-scoring/svc.yaml
  - ./ml-scoring/hap.yaml
  - ./ml-scoring/service_monitor.yaml
  - ./misc.yaml
  - ./rocksdb.yaml
  - ./create_features/roles.yaml
  - ./create_features/job.yaml
  - ./grafana.yaml
