apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: score-ep-ingress
  namespace: scoring

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /score
            pathType: Prefix
            backend:
              service:
                name: scoring
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scoring-ingress
  namespace: scoring

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scoring
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 3000
