apiVersion: v1
kind: PersistentVolume
metadata:
  name: features-db-pv
  namespace: scoring
  labels:
    name: features-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /rocksdb
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: features-db-pvc
  namespace: scoring
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: features-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
