global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "feature_server"
    static_configs:
      - targets: ["feature_server:8080"]
  - job_name: "scoring_server"
    static_configs:
      - targets: ["scoring_server:8080"]
