apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scoring
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - scoring
  selector:
    matchLabels:
      app: scoring
  endpoints:
    - port: scoring
      interval: 15s
