{
 "title": "Scoring Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Score Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(api_incoming_requests{endpoint=\"/score\", instance=~\"scoring_server.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "score Response codes / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(statuscode, endpoint) (rate(api_response_code{endpoint=\"/score\", instance=~\"scoring_server.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "score 99th perc response time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(api_response_time_bucket{endpoint=\"/score\", instance=~\"scoring_server.*\"}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}