apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../resources/
  - ./efscsi.yaml

patches:
  - path: ./patches/scoring-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: scoring

  - path: ./patches/updates-patch.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: feature-generator

  - path: ./patches/rocksdb-pv.yaml
    target:
      version: v1
      kind: PersistentVolume
      name: features-db-pv

  - path: ./patches/rocksdb-pvc.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: features-db-pvc
