envoy:
  service:

    type: LoadBalancer
    containerPorts:
      http: 80
      https: 443  # Use 443 for HTTPS, not 80
    # Use Network Load Balancer (as you're already on NLB via AWS LB Controller)
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 60
    targetMemory: 60

  resources:
    limits:
      cpu: 250m
      memory: 250M
    requests:
      cpu: 250m
      memory: 250M

contour:
  resources:
    limits:
      cpu: 500m
      memory: 700M
    requests:
      cpu: 500m
      memory: 700M

metrics:
  ## Prometheus Operator service monitors
  ##
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus

