# nginx-values.yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing # or "internal"

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75

  extraArgs:
    metrics-per-host: false
  metrics:
    enabled: true

    serviceMonitor:
      enabled: true
      namespace: monitoring # namespace where Prometheus is running
      interval: 15s
      additionalLabels:
        release: prometheus
  admissionWebhooks:
    enabled: false # disable if you don’t need admission webhooks

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi
