# nginx-values.yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing # or "internal"
      service.kubernetes.io/topology-mode: auto
    externalTrafficPolicy: Local

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75

  extraArgs:
    metrics-per-host: false
  metrics:
    enabled: true

    serviceMonitor:
      enabled: true
      namespace: monitoring # namespace where Prometheus is running
      interval: 15s
      additionalLabels:
        release: prometheus
  admissionWebhooks:
    enabled: false # disable if you don’t need admission webhooks

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi

  topologySpreadConstraints:
    - maxSkew: 1 # Allows for at most one more pod in one AZ than another
      topologyKey: topology.kubernetes.io/zone # Spread across Availability Zones
      whenUnsatisfiable: DoNotSchedule # Pods won't be scheduled if this constraint can't be met
                                       # Consider "ScheduleAnyway" if absolute availability is higher priority than strict spreading
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ngix-ingress
          app.kubernetes.io/name: ingress-nginx

  # enableTopologyAwareRouting: true
