apiVersion: batch/v1
kind: Job
metadata:
  name: feature-generator
  namespace: scoring
spec:
  template:
    spec:
      serviceAccountName: feature-notifier
      containers:
        - name: feature-writer
          image: ml-update-features:dev
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 4
              memory: 7.7G
            limits:
              cpu: 4
              memory: 7.7G
          env:
            - name: FEATURES_PATH
              value: /usr/src/app/rocksdb
          volumeMounts:
            - name: rocksdb-volume
              mountPath: /usr/src/app/rocksdb
      restartPolicy: Never
      volumes:
        - name: rocksdb-volume
          persistentVolumeClaim:
            claimName: features-db-pvc
  backoffLimit: 2
