apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../resources/
  - ./metallb.yaml

patches:
  - path: ./patches/hpa-scoring-replicas.yaml
    target:
      group: autoscaling
      version: v1
      kind: HorizontalPodAutoscaler
      name: scoring-hpa
  - path: ./patches/rocksdb.yaml
    target:
      version: v1
      kind: PersistentVolume
      name: features-db-pv

commonLabels:
  env: dev
